# This is a basic workflow to help you get started with Actions

name: linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
   paths:
    - 'linux'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download current snapshot
        run: curl https://github.com/Parksy-00/linux/archive/$(git rev-parse HEAD:linux).zip -o cur_linux.zip
       
      - run: |
          sudo apt-get install p7zip-full
          7z x cur_linux.zip

      - run: ./install-deps.sh
      - run: ./build-linux.sh cur_linux tinyconfig
